language: scala
sudo: false
jdk:
- oraclejdk8
# List of environment variables are
# - SONATYPE_USERNAME
# - SONATYPE_PASSWORD
env:
  matrix:
  - BUILD_LABEL=4.0.${TRAVIS_BUILD_NUMBER}
  global:
  - secure: WNb8qjMw+svqsW51cZcxvYy3Z8fqJrB3a0x+KjR064qv8Y6xIc+Y/LDG78WHSG6NQemW8RiEVv85ip3VzbXUOq8h4PUlRe/prBSPVcC5ano12NK5E1hUlx7njrGpEtgMYQuh87ByEDcn1UPuKE72RMwELDGmI8FWEV6vaQpCnAtKYcR476g7Nlh2yFSBs+++2mEdRkY9ADLjOv67wLtbpS6KUlevu5V1z73njPqJ2vOkFzO5U1AK9UMUPHnsXqECm/wzPOqQvBp+2JwSBhvHbcK2duJ8DXj3eH0vx9YdCv1FyOGZBLdTRQhBjPOdsicbKir5BDN13l+DdYb0hgLORXLf/QonO+iO+5z5HpkXKsecKcXdE2CqHyOYXkNzhbaNMy6dHVlCdgvRW3lsglo8mL27aNlgcPOhLCV+Linte5QMpPzoUEQaykPTqBnQSVdn9th2SxMxY7mSamCFX8JlOE82hqTF0074GexqLHtLLQmbJKpDsqCddSsCcJ37pjqg/u5XuMPOcLtCgJt2m6dyKC9tEPIfgUO+tRxDaNYjv67XXRHk3yR/h2RqnApgn2QriX93hNUjiADLxx4fxAfNsTQHATYivjD7SH33ryyrR8agNTv3CAvAQH20/NtSXJKtt7k+sr2WcdAZSx8Y7g/sDar5X8wakZwtm/1oOBGgwcg=
  - secure: PcraIZXoMP9ru/m5k/ztEOTPA+qxkZbQLMxEmdAizVDvnvfVQVxAneCtbjOzb7u773YRpV1qSY2e81uOCzH4cSqp5672e5dHHEyN5LuJLH0DbpbbgVOdKRa9cYLq5pavNeEBZTFrmXGdXLV2U9YdrG0PtSyzSLsCEVEUMhs4f6Y6y2dWJ9SKo0eWlclwYNO2wNoimf6f/ekA43DUDYs6kBlKseZUXNShSkTp2utVq0YnxgfmVffEhdsUGIdKd27aEImZBIGbLrGWqUdhP4vFpF7O+ZvixalmhGpq/4SB9UmbEX9BROvj84brHf3fH3g4W4Ka8UqHK8JQ3JHePx+Y34YXhv/im7aip3yn9U9WLnCOAa7LQt1CHm31mXWmKuAt4G6Qc4J8ch8aqBU9tl4wcp6SNGHYrv7eiq09OKoyYpVe5ZPVHh+PjkHXmznT4ywHCGa68kHYgIL3jO4gYSDxzgYudgOlwC5vU5ipdE/yP460ya28m2PKAnWM+TSbUdSkuZcVcWNgTCUr7KBw4eK3qK/XOqxG7DXsbzZE2I76HozrygubfMpSJc339Q/EsXI67ersjz1aPgXlq/ikppahRufikgu30p8S9TcHd4C7P0ui9HcqWdCRz3mt7GBySfosIN90HdySo+lCrTDG84tm70Hrj9g0K6bJKBTnmYH0pGc=
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script: "./build.sh"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
before_install:
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASSWORD -in .travis/secring.gpg.enc -out local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASSWORD -in .travis/pubring.gpg.enc -out local.pubring.gpg -d
before_deploy:
- ".travis/publish.sh"
- "./deploy.sh"
- nvm install v7.8.0
- nvm use v7.8.0
- npm install -g yarn
- "./docs/deploy.sh"
deploy:
- provider: releases
  api_key:
    secure: C+vg/B+z+fqEtWh80ovIRruknQgG1sL/OaM5E4xhy589uGi6MDHrAZS9YuZ5ViQFjfCGGo+XzS8Up86yYPMTr1F+kRTViO/pGZst1yA8xO5o7Ep1Xd+q2mItpAhGMPJU0q41G9gIg0epF0OyIuYeXcAXo5h0LsNBS6PAQQEfpJQ=
  file:
  - "./fetch/target/s3fetch-assembly-${TRAVIS_TAG}.jar"
  - "./publish/target/s3publish-assembly-${TRAVIS_TAG}.jar"
  - "./material/target/s3material-assembly-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  local_dir: docs/_book
  skip_cleanup: true
  target_branch: gh-pages
  github_token:
    secure: C+vg/B+z+fqEtWh80ovIRruknQgG1sL/OaM5E4xhy589uGi6MDHrAZS9YuZ5ViQFjfCGGo+XzS8Up86yYPMTr1F+kRTViO/pGZst1yA8xO5o7Ep1Xd+q2mItpAhGMPJU0q41G9gIg0epF0OyIuYeXcAXo5h0LsNBS6PAQQEfpJQ=
  email: manoj@indix.com
  name: Manoj
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: HQdcZwqDY9+vGW7N9YZ2tFeU50SgqrWEQefI/injWVcndkAL7U/TFOoFvyOdxPZA1sya3aKUyAfVVv7BzMdPUfas41LgYj+iSWAaidiwqrJMp3lkvvALoXId9IDrdWcbhqJ4F51dfO8ck6Jf0S9cXtXC8/dSunWJORdr9ycgkxs=
    on_success: change
    on_failure: always
