language: scala
sudo: false
jdk:
- oraclejdk8
# List of environment variables are
# - SONATYPE_USERNAME
# - SONATYPE_PASSWORD
env:
- BUILD_LABEL=4.0.${TRAVIS_BUILD_NUMBER}
  global:
    - secure: kpjH7aTsEKFRw9rcQs7svGeeScUyo084hl+ugyUcgM73r6TMHgr3Y7UwHSGKKpa1JtTkpfUiJZclGbKdoX5NHN8rGMOTuJtcyl9Nwo9aYpIMf0/rFNBlmH/J3PZqWx0cx+1ajggmruOfez5AN9exHcdKV1xVEKvd5PxKaJki5QikdN+pMeXTnUKp4yWV5UlEvbV50+iG0SUdeuKPpTZnM1zqhR2J/1IErXXVoTDmc01AxroHBIpFO7BOpqgui1ID5JjfJtBSdlU4aU31p70keyalsO+yy/BBt7Vwz3T5sCBKWUjA0FJBY6GSV8STEwnT1I7i6McXTJ2Rxe5GNz9PsDQ+KmEwofzFokocq5V3BXqSWhHhLAELpo6YTDoE0eqhaodEIrOc+4AU1ZFTTaARFyqonOjdIqXSZGyRP9JeFo18ZBinZPRpkjtUoiXoQsagS2vwc//+Z4MaIm8MLEYbfZ6SOhSJZpIOtJNj+us4iUJ05nLt0epzMQh2Ih4Qy55leylLz3HMAEMXwGwiBsAYg98t1WPM0TFJ4KCTpM8fkk+EIUW1zmf/GbLQuSw0xbOtbjE+dfTsds7nDUN30jaXoRw1M2KfcRIiPxSDn4YxbxJXVyVrKXoec4Nary3F25cvGYPM3TZOTxmE7SMZAUGF0Geumttbo7Tq2qPWymrV/i4=
    - secure: CXWDMYkzT4xIjjhP6Y5NchZivTTZLCaJi1B3yKfDRt+ylo+n/zUQH8AYr2W4ZPRpGVDjq+DU6h4FS3U1lc+ggG+5r5mRdbKHjul1bX00TRQxDJmu4+dgkL8id+dazrHYpX33wIyFVQR8wCVhmBec8dfBdfxnNPzkyOM3vdpXBJ9IssgMuILXYfPc828NDR5mdUmtdVw1ycNZMJ0arFbwAXypOTLRuUFA612vRTFRovw+TtoGjBZ0EjG6irko+DrwOOU13afjTlFRyCmGnD1tYPUb/lOQ6N1rP0Elc9dY9weW9SfMsnNDt74XoQaXKrXEx61NTAKfb248ipRGf8Iqmmw79i3ZRQdFoNWPq16vg2BzKaky8cpsaCFD6Q+iHK76pdBSbXgeTz1HVJe9HALT/TCWgIO4PwxqM0yniqGNGreoH+F3IDRApUQZPLKJYu18955BGVArFUSQArLd8gkIsgrfKQm4QAC5H/fQugkS82Lh9hO0Y3t926RKHJU65jCmJMica3kwTQk1l/udjQKAtTRkkJlKsjhkf4XKbm568VwDhW4XxkAedlQhHMeed8o107hFbaGT/zxLpvrpv+RjFTG8eUqswDF9Tp+izmyBvwiQmYFZVJSrmUtyy61rKxhu6bo7VZ2qLogPGz90vgPAli8h4bMmNv3PBz+dblD+Zj4=
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script: "./build.sh"
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
before_install:
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASSWORD -in .travis/secring.gpg.enc -out local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASSWORD -in .travis/pubring.gpg.enc -out local.pubring.gpg -d
before_deploy:
  - ".travis/publish.sh"
  - "./deploy.sh"
  - nvm install v7.8.0
  - nvm use v7.8.0
  - npm install -g yarn
  - "./docs/deploy.sh"
deploy:
- provider: releases
  api_key:
    secure: C+vg/B+z+fqEtWh80ovIRruknQgG1sL/OaM5E4xhy589uGi6MDHrAZS9YuZ5ViQFjfCGGo+XzS8Up86yYPMTr1F+kRTViO/pGZst1yA8xO5o7Ep1Xd+q2mItpAhGMPJU0q41G9gIg0epF0OyIuYeXcAXo5h0LsNBS6PAQQEfpJQ=
  file:
  - "./fetch/target/s3fetch-assembly-${TRAVIS_TAG}.jar"
  - "./publish/target/s3publish-assembly-${TRAVIS_TAG}.jar"
  - "./material/target/s3material-assembly-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  local_dir: docs/_book
  skip_cleanup: true
  target_branch: gh-pages
  github_token:
    secure: C+vg/B+z+fqEtWh80ovIRruknQgG1sL/OaM5E4xhy589uGi6MDHrAZS9YuZ5ViQFjfCGGo+XzS8Up86yYPMTr1F+kRTViO/pGZst1yA8xO5o7Ep1Xd+q2mItpAhGMPJU0q41G9gIg0epF0OyIuYeXcAXo5h0LsNBS6PAQQEfpJQ=
  email: manoj@indix.com
  name: Manoj
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: HQdcZwqDY9+vGW7N9YZ2tFeU50SgqrWEQefI/injWVcndkAL7U/TFOoFvyOdxPZA1sya3aKUyAfVVv7BzMdPUfas41LgYj+iSWAaidiwqrJMp3lkvvALoXId9IDrdWcbhqJ4F51dfO8ck6Jf0S9cXtXC8/dSunWJORdr9ycgkxs=
    on_success: change
    on_failure: always
